# Generated by Django 4.1.6 on 2023-02-25 14:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_rename_post_blogpost"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogpost",
            options={"ordering": ("title",)},
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ("title",)},
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={"ordering": ("title",)},
        ),
    ]
