# Generated by Django 4.1.6 on 2023-02-05 18:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_profile", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="slug",
            field=models.SlugField(max_length=200),
        ),
    ]
