# Generated by Django 4.1.6 on 2023-02-26 07:46

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):
    dependencies = [
        ("user_profile", "0002_alter_profile_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="info",
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
